#pragma once

#define SCREEN_WIDTH 400
#define SCREEN_HEIGHT 400
#define PIXEL_COUNT SCREEN_WIDTH * SCREEN_HEIGHT
#define ONE_PARTICLE 4
#define CHANNEL_COUNT PIXEL_COUNT * ONE_PARTICLE
#define PARTICLE_PER_ROW SCREEN_WIDTH * ONE_PARTICLE
#define PARTICLE_PER_COLUMN SCREEN_HEIGHT * ONE_PARTICLE
#define ACCELERATION 0.01f